name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ GH_TOKEN }}
          GIST_ID: d47aa9cf4b802d56cc1f5747430ce968
          TIMEZONE: Asia/Seoul
